# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
name: '데브경수'
url: 'https://waterglasstoon.github.io'
instaurl: 'https://www.instagram.com/waterglasstoon'
description: ''
thumbnail: '/images/thumbnail.png'
titleimg: '/images/hello_from_kyungsoo.png'
mail: "waterglass.toon@gmail.com"
author: 'waterglasstoon'

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
sass:
  sass_dir: _sass
  style: :compressed

exclude: [Gemfile, Gemfile.lock, README.md]